graph TD
    kprintf_stub.c--> include/kprintf.h
    kpanic.c--> sys/kassert.h
    kpanic.c--> klib/include/kprintf.h
    kpanic.c--> stdarg.h
    kstring.c--> kstring.h
    kstring.c--> minix/kernel_types.h
    kmemory.c--> kmemory.h
    kmemory.c--> minix/kernel_types.h
    include/kprintf.h--> minix/kernel_types.h
    include/kprintf.h--> stdarg.h
    include/kmemory.h--> minix/kernel_types.h
    include/kstring.h--> minix/kernel_types.h
