graph TD
    sys/bind.c--> sys/cdefs.h
    sys/bind.c--> namespace.h
    sys/bind.c--> lib.h
    sys/bind.c--> unistd.h
    sys/bind.c--> stdint.h
    sys/bind.c--> stdlib.h
    sys/bind.c--> limits.h
    sys/bind.c--> errno.h
    sys/bind.c--> stdio.h
    sys/bind.c--> string.h
    sys/bind.c--> sys/ioctl.h
    sys/bind.c--> sys/socket.h
    sys/bind.c--> sys/types.h
    sys/bind.c--> sys/stat.h
    sys/bind.c--> netinet/in.h
    sys/bind.c--> net/gen/in.h
    sys/bind.c--> net/gen/tcp.h
    sys/bind.c--> net/gen/tcp_io.h
    sys/bind.c--> net/gen/udp.h
    sys/bind.c--> net/gen/udp_io.h
    sys/bind.c--> sys/un.h
    sys/bind.c--> minix/config.h
    sys/bind.c--> minix/const.h
    sys/clock_getres.c--> sys/cdefs.h
    sys/clock_getres.c--> lib.h
    sys/clock_getres.c--> namespace.h
    sys/clock_getres.c--> string.h
    sys/clock_getres.c--> sys/time.h
    sys/listen.c--> sys/cdefs.h
    sys/listen.c--> namespace.h
    sys/listen.c--> lib.h
    sys/listen.c--> errno.h
    sys/listen.c--> stdio.h
    sys/listen.c--> string.h
    sys/listen.c--> sys/ioctl.h
    sys/listen.c--> sys/socket.h
    sys/listen.c--> netinet/in.h
    sys/listen.c--> net/gen/in.h
    sys/listen.c--> net/gen/tcp.h
    sys/listen.c--> net/gen/tcp_io.h
    sys/listen.c--> net/gen/udp.h
    sys/listen.c--> net/gen/udp_io.h
    sys/chroot.c--> sys/cdefs.h
    sys/chroot.c--> namespace.h
    sys/chroot.c--> lib.h
    sys/chroot.c--> string.h
    sys/chroot.c--> unistd.h
    sys/reboot.c--> sys/cdefs.h
    sys/reboot.c--> lib.h
    sys/reboot.c--> unistd.h
    sys/reboot.c--> namespace.h
    sys/reboot.c--> string.h
    sys/reboot.c--> sys/reboot.h
    sys/utimensat.c--> sys/cdefs.h
    sys/utimensat.c--> namespace.h
    sys/utimensat.c--> lib.h
    sys/utimensat.c--> sys/stat.h
    sys/utimensat.c--> fcntl.h
    sys/utimensat.c--> string.h
    sys/utimensat.c--> limits.h
    sys/utimensat.c--> errno.h
    sys/sync.c--> sys/cdefs.h
    sys/sync.c--> lib.h
    sys/sync.c--> namespace.h
    sys/sync.c--> string.h
    sys/sync.c--> unistd.h
    sys/pipe.c--> sys/cdefs.h
    sys/pipe.c--> namespace.h
    sys/pipe.c--> lib.h
    sys/pipe.c--> string.h
    sys/pipe.c--> unistd.h
    sys/pwrite.c--> sys/cdefs.h
    sys/pwrite.c--> namespace.h
    sys/pwrite.c--> errno.h
    sys/pwrite.c--> unistd.h
    sys/minix_rs.c--> sys/cdefs.h
    sys/minix_rs.c--> minix/com.h
    sys/minix_rs.c--> minix/config.h
    sys/minix_rs.c--> minix/ipc.h
    sys/minix_rs.c--> minix/endpoint.h
    sys/minix_rs.c--> minix/sysutil.h
    sys/minix_rs.c--> minix/syslib.h
    sys/minix_rs.c--> minix/const.h
    sys/minix_rs.c--> minix/type.h
    sys/minix_rs.c--> minix/ds.h
    sys/minix_rs.c--> minix/rs.h
    sys/minix_rs.c--> stdio.h
    sys/minix_rs.c--> stdlib.h
    sys/minix_rs.c--> errno.h
    sys/minix_rs.c--> string.h
    sys/minix_rs.c--> lib.h
    sys/dup.c--> sys/cdefs.h
    sys/dup.c--> namespace.h
    sys/dup.c--> lib.h
    sys/dup.c--> fcntl.h
    sys/dup.c--> unistd.h
    sys/_ucontext.c--> sys/cdefs.h
    sys/_ucontext.c--> namespace.h
    sys/_ucontext.c--> lib.h
    sys/_ucontext.c--> machine/stackframe.h
    sys/_ucontext.c--> sys/cdefs.h
    sys/_ucontext.c--> ucontext.h
    sys/_ucontext.c--> signal.h
    sys/_ucontext.c--> stdarg.h
    sys/_ucontext.c--> stdlib.h
    sys/_ucontext.c--> unistd.h
    sys/_ucontext.c--> stdint.h
    sys/_ucontext.c--> stdio.h
    sys/lutimes.c--> sys/cdefs.h
    sys/lutimes.c--> namespace.h
    sys/lutimes.c--> lib.h
    sys/lutimes.c--> sys/stat.h
    sys/lutimes.c--> sys/time.h
    sys/lutimes.c--> fcntl.h
    sys/lutimes.c--> string.h
    sys/lutimes.c--> errno.h
    sys/geteuid.c--> sys/cdefs.h
    sys/geteuid.c--> namespace.h
    sys/geteuid.c--> lib.h
    sys/geteuid.c--> string.h
    sys/geteuid.c--> unistd.h
    sys/umask.c--> sys/cdefs.h
    sys/umask.c--> lib.h
    sys/umask.c--> namespace.h
    sys/umask.c--> string.h
    sys/umask.c--> sys/stat.h
    sys/pread.c--> sys/cdefs.h
    sys/pread.c--> namespace.h
    sys/pread.c--> errno.h
    sys/pread.c--> unistd.h
    sys/init.c--> stdio.h
    sys/init.c--> minix/ipc.h
    sys/settimeofday.c--> sys/cdefs.h
    sys/settimeofday.c--> lib.h
    sys/settimeofday.c--> namespace.h
    sys/settimeofday.c--> sys/time.h
    sys/settimeofday.c--> time.h
    sys/gcov_flush_sys.c--> lib.h
    sys/gcov_flush_sys.c--> string.h
    sys/gcov_flush_sys.c--> minix/gcov.h
    sys/chmod.c--> sys/cdefs.h
    sys/chmod.c--> namespace.h
    sys/chmod.c--> lib.h
    sys/chmod.c--> string.h
    sys/chmod.c--> sys/stat.h
    sys/gettimeofday.c--> sys/cdefs.h
    sys/gettimeofday.c--> namespace.h
    sys/gettimeofday.c--> lib.h
    sys/gettimeofday.c--> string.h
    sys/gettimeofday.c--> sys/time.h
    sys/loadname.c--> sys/cdefs.h
    sys/loadname.c--> lib.h
    sys/loadname.c--> namespace.h
    sys/loadname.c--> string.h
    sys/pathconf.c--> sys/cdefs.h
    sys/pathconf.c--> namespace.h
    sys/pathconf.c--> lib.h
    sys/pathconf.c--> fcntl.h
    sys/pathconf.c--> errno.h
    sys/pathconf.c--> unistd.h
    sys/brk.c--> sys/cdefs.h
    sys/brk.c--> namespace.h
    sys/brk.c--> lib.h
    sys/brk.c--> string.h
    sys/brk.c--> unistd.h
    sys/sprofile.c--> sys/cdefs.h
    sys/sprofile.c--> namespace.h
    sys/sprofile.c--> lib.h
    sys/sprofile.c--> string.h
    sys/sprofile.c--> minix/profile.h
    sys/ptrace.c--> sys/cdefs.h
    sys/ptrace.c--> namespace.h
    sys/ptrace.c--> lib.h
    sys/ptrace.c--> string.h
    sys/ptrace.c--> sys/ptrace.h
    sys/getegid.c--> sys/cdefs.h
    sys/getegid.c--> namespace.h
    sys/getegid.c--> lib.h
    sys/getegid.c--> string.h
    sys/getegid.c--> unistd.h
    sys/kill.c--> sys/cdefs.h
    sys/kill.c--> namespace.h
    sys/kill.c--> lib.h
    sys/kill.c--> string.h
    sys/kill.c--> signal.h
    sys/getgid.c--> sys/cdefs.h
    sys/getgid.c--> namespace.h
    sys/getgid.c--> lib.h
    sys/getgid.c--> string.h
    sys/getgid.c--> unistd.h
    sys/clock_gettime.c--> sys/cdefs.h
    sys/clock_gettime.c--> lib.h
    sys/clock_gettime.c--> namespace.h
    sys/clock_gettime.c--> string.h
    sys/clock_gettime.c--> sys/time.h
    sys/getppid.c--> sys/cdefs.h
    sys/getppid.c--> namespace.h
    sys/getppid.c--> lib.h
    sys/getppid.c--> string.h
    sys/getppid.c--> unistd.h
    sys/socketpair.c--> sys/cdefs.h
    sys/socketpair.c--> namespace.h
    sys/socketpair.c--> lib.h
    sys/socketpair.c--> string.h
    sys/socketpair.c--> errno.h
    sys/socketpair.c--> stdio.h
    sys/socketpair.c--> fcntl.h
    sys/socketpair.c--> unistd.h
    sys/socketpair.c--> net/netlib.h
    sys/socketpair.c--> sys/ioctl.h
    sys/socketpair.c--> sys/ioc_net.h
    sys/socketpair.c--> sys/socket.h
    sys/socketpair.c--> sys/stat.h
    sys/socketpair.c--> sys/un.h
    sys/rmdir.c--> sys/cdefs.h
    sys/rmdir.c--> lib.h
    sys/rmdir.c--> namespace.h
    sys/rmdir.c--> string.h
    sys/rmdir.c--> unistd.h
    sys/readlink.c--> sys/cdefs.h
    sys/readlink.c--> lib.h
    sys/readlink.c--> namespace.h
    sys/readlink.c--> unistd.h
    sys/readlink.c--> string.h
    sys/unlink.c--> sys/cdefs.h
    sys/unlink.c--> lib.h
    sys/unlink.c--> namespace.h
    sys/unlink.c--> string.h
    sys/unlink.c--> unistd.h
    sys/sendto.c--> sys/cdefs.h
    sys/sendto.c--> namespace.h
    sys/sendto.c--> lib.h
    sys/sendto.c--> assert.h
    sys/sendto.c--> errno.h
    sys/sendto.c--> stdio.h
    sys/sendto.c--> stdlib.h
    sys/sendto.c--> string.h
    sys/sendto.c--> unistd.h
    sys/sendto.c--> sys/ioctl.h
    sys/sendto.c--> sys/socket.h
    sys/sendto.c--> netinet/in.h
    sys/sendto.c--> net/gen/in.h
    sys/sendto.c--> net/gen/ip_hdr.h
    sys/sendto.c--> net/gen/ip_io.h
    sys/sendto.c--> net/gen/tcp.h
    sys/sendto.c--> net/gen/tcp_io.h
    sys/sendto.c--> net/gen/udp.h
    sys/sendto.c--> net/gen/udp_hdr.h
    sys/sendto.c--> net/gen/udp_io.h
    sys/setgroups.c--> sys/cdefs.h
    sys/setgroups.c--> lib.h
    sys/setgroups.c--> namespace.h
    sys/setgroups.c--> string.h
    sys/setgroups.c--> unistd.h
    sys/svrctl.c--> lib.h
    sys/svrctl.c--> stdio.h
    sys/svrctl.c--> string.h
    sys/svrctl.c--> sys/svrctl.h
    sys/getitimer.c--> sys/cdefs.h
    sys/getitimer.c--> namespace.h
    sys/getitimer.c--> lib.h
    sys/getitimer.c--> string.h
    sys/getitimer.c--> sys/time.h
    sys/fstatvfs.c--> sys/cdefs.h
    sys/fstatvfs.c--> namespace.h
    sys/fstatvfs.c--> lib.h
    sys/fstatvfs.c--> string.h
    sys/fstatvfs.c--> sys/statvfs.h
    sys/__getlogin.c--> sys/cdefs.h
    sys/__getlogin.c--> namespace.h
    sys/__getlogin.c--> lib.h
    sys/__getlogin.c--> pwd.h
    sys/__getlogin.c--> unistd.h
    sys/__getlogin.c--> string.h
    sys/__getlogin.c--> stdio.h
    sys/__getlogin.c--> extern.h
    sys/mkdir.c--> sys/cdefs.h
    sys/mkdir.c--> namespace.h
    sys/mkdir.c--> lib.h
    sys/mkdir.c--> sys/stat.h
    sys/mkdir.c--> string.h
    sys/symlink.c--> sys/cdefs.h
    sys/symlink.c--> lib.h
    sys/symlink.c--> namespace.h
    sys/symlink.c--> string.h
    sys/symlink.c--> unistd.h
    sys/kernel_utils.c--> sys/cdefs.h
    sys/kernel_utils.c--> namespace.h
    sys/kernel_utils.c--> lib.h
    sys/kernel_utils.c--> minix/param.h
    sys/kernel_utils.c--> assert.h
    sys/shmctl.c--> sys/cdefs.h
    sys/shmctl.c--> lib.h
    sys/shmctl.c--> namespace.h
    sys/shmctl.c--> minix/rs.h
    sys/shmctl.c--> lib.h
    sys/shmctl.c--> sys/types.h
    sys/shmctl.c--> sys/ipc.h
    sys/shmctl.c--> sys/shm.h
    sys/shmctl.c--> stdlib.h
    sys/shmctl.c--> errno.h
    sys/shmctl.c--> string.h
    sys/truncate.c--> sys/cdefs.h
    sys/truncate.c--> namespace.h
    sys/truncate.c--> lib.h
    sys/truncate.c--> minix/u64.h
    sys/truncate.c--> string.h
    sys/truncate.c--> unistd.h
    sys/getpgrp.c--> sys/cdefs.h
    sys/getpgrp.c--> namespace.h
    sys/getpgrp.c--> lib.h
    sys/getpgrp.c--> string.h
    sys/getpgrp.c--> unistd.h
    sys/getsid.c--> sys/cdefs.h
    sys/getsid.c--> namespace.h
    sys/getsid.c--> lib.h
    sys/getsid.c--> unistd.h
    sys/getsid.c--> string.h
    sys/mmap.c--> sys/cdefs.h
    sys/mmap.c--> namespace.h
    sys/mmap.c--> lib.h
    sys/mmap.c--> minix/u64.h
    sys/mmap.c--> minix/vm.h
    sys/mmap.c--> sys/mman.h
    sys/mmap.c--> stdarg.h
    sys/mmap.c--> string.h
    sys/mmap.c--> errno.h
    sys/recvfrom.c--> sys/cdefs.h
    sys/recvfrom.c--> namespace.h
    sys/recvfrom.c--> lib.h
    sys/recvfrom.c--> assert.h
    sys/recvfrom.c--> errno.h
    sys/recvfrom.c--> stdlib.h
    sys/recvfrom.c--> stdio.h
    sys/recvfrom.c--> string.h
    sys/recvfrom.c--> unistd.h
    sys/recvfrom.c--> sys/ioctl.h
    sys/recvfrom.c--> sys/socket.h
    sys/recvfrom.c--> netinet/in.h
    sys/recvfrom.c--> net/gen/in.h
    sys/recvfrom.c--> net/gen/tcp.h
    sys/recvfrom.c--> net/gen/tcp_io.h
    sys/recvfrom.c--> net/gen/udp.h
    sys/recvfrom.c--> net/gen/udp_hdr.h
    sys/recvfrom.c--> net/gen/udp_io.h
    sys/recvfrom.c--> net/gen/ip_hdr.h
    sys/recvfrom.c--> net/gen/ip_io.h
    sys/getpeername.c--> sys/cdefs.h
    sys/getpeername.c--> namespace.h
    sys/getpeername.c--> lib.h
    sys/getpeername.c--> errno.h
    sys/getpeername.c--> stdio.h
    sys/getpeername.c--> string.h
    sys/getpeername.c--> sys/ioctl.h
    sys/getpeername.c--> sys/socket.h
    sys/getpeername.c--> netinet/in.h
    sys/getpeername.c--> net/gen/in.h
    sys/getpeername.c--> net/gen/tcp.h
    sys/getpeername.c--> net/gen/tcp_io.h
    sys/getpeername.c--> net/gen/udp.h
    sys/getpeername.c--> net/gen/udp_io.h
    sys/getpeername.c--> sys/un.h
    sys/setsid.c--> sys/cdefs.h
    sys/setsid.c--> lib.h
    sys/setsid.c--> namespace.h
    sys/setsid.c--> string.h
    sys/setsid.c--> unistd.h
    sys/connect.c--> sys/cdefs.h
    sys/connect.c--> namespace.h
    sys/connect.c--> lib.h
    sys/connect.c--> minix/config.h
    sys/connect.c--> errno.h
    sys/connect.c--> fcntl.h
    sys/connect.c--> stdio.h
    sys/connect.c--> stdlib.h
    sys/connect.c--> unistd.h
    sys/connect.c--> string.h
    sys/connect.c--> sys/ioctl.h
    sys/connect.c--> sys/socket.h
    sys/connect.c--> sys/types.h
    sys/connect.c--> sys/stat.h
    sys/connect.c--> netinet/in.h
    sys/connect.c--> net/gen/in.h
    sys/connect.c--> net/gen/tcp.h
    sys/connect.c--> net/gen/tcp_io.h
    sys/connect.c--> net/gen/udp.h
    sys/connect.c--> net/gen/udp_io.h
    sys/connect.c--> minix/const.h
    sys/sizeup.c--> sys/cdefs.h
    sys/sizeup.c--> namespace.h
    sys/sizeup.c--> lib.h
    sys/sizeup.c--> minix/u64.h
    sys/sizeup.c--> sys/types.h
    sys/sizeup.c--> sys/stat.h
    sys/sizeup.c--> stdio.h
    sys/sizeup.c--> errno.h
    sys/sizeup.c--> fcntl.h
    sys/sizeup.c--> limits.h
    sys/sizeup.c--> stdlib.h
    sys/sizeup.c--> string.h
    sys/sizeup.c--> time.h
    sys/sizeup.c--> unistd.h
    sys/sizeup.c--> minix/config.h
    sys/sizeup.c--> minix/const.h
    sys/sizeup.c--> minix/type.h
    sys/sizeup.c--> minix/minlib.h
    sys/sizeup.c--> minix/partition.h
    sys/sizeup.c--> sys/ioctl.h
    sys/sizeup.c--> sys/ioc_disk.h
    sys/sizeup.c--> unistd.h
    sys/sigprocmask.c--> sys/cdefs.h
    sys/sigprocmask.c--> sys/types.h
    sys/sigprocmask.c--> sys/sigtypes.h
    sys/sigprocmask.c--> sys/signal.h
    sys/sigprocmask.c--> lib.h
    sys/sigprocmask.c--> string.h
    sys/sigprocmask.c--> namespace.h
    sys/sigprocmask.c--> string.h
    sys/sigprocmask.c--> signal.h
    sys/_exit.c--> sys/cdefs.h
    sys/_exit.c--> namespace.h
    sys/_exit.c--> lib.h
    sys/_exit.c--> string.h
    sys/_exit.c--> unistd.h
    sys/setuid.c--> sys/cdefs.h
    sys/setuid.c--> lib.h
    sys/setuid.c--> namespace.h
    sys/setuid.c--> string.h
    sys/setuid.c--> unistd.h
    sys/fcntl.c--> sys/cdefs.h
    sys/fcntl.c--> namespace.h
    sys/fcntl.c--> lib.h
    sys/fcntl.c--> string.h
    sys/fcntl.c--> fcntl.h
    sys/fcntl.c--> stdarg.h
    sys/futimes.c--> sys/cdefs.h
    sys/futimes.c--> namespace.h
    sys/futimes.c--> lib.h
    sys/futimes.c--> string.h
    sys/futimes.c--> sys/stat.h
    sys/futimes.c--> sys/time.h
    sys/read.c--> sys/cdefs.h
    sys/read.c--> lib.h
    sys/read.c--> namespace.h
    sys/read.c--> string.h
    sys/read.c--> unistd.h
    sys/getsockopt.c--> sys/cdefs.h
    sys/getsockopt.c--> namespace.h
    sys/getsockopt.c--> lib.h
    sys/getsockopt.c--> assert.h
    sys/getsockopt.c--> errno.h
    sys/getsockopt.c--> stdio.h
    sys/getsockopt.c--> string.h
    sys/getsockopt.c--> sys/ioctl.h
    sys/getsockopt.c--> sys/socket.h
    sys/getsockopt.c--> sys/types.h
    sys/getsockopt.c--> sys/ucred.h
    sys/getsockopt.c--> netinet/tcp.h
    sys/getsockopt.c--> net/gen/in.h
    sys/getsockopt.c--> net/gen/tcp.h
    sys/getsockopt.c--> net/gen/tcp_io.h
    sys/getsockopt.c--> net/gen/udp.h
    sys/getsockopt.c--> net/gen/udp_io.h
    sys/getsockopt.c--> minix/type.h
    sys/accept.c--> sys/cdefs.h
    sys/accept.c--> namespace.h
    sys/accept.c--> lib.h
    sys/accept.c--> errno.h
    sys/accept.c--> fcntl.h
    sys/accept.c--> stdio.h
    sys/accept.c--> stdlib.h
    sys/accept.c--> unistd.h
    sys/accept.c--> string.h
    sys/accept.c--> sys/ioctl.h
    sys/accept.c--> sys/socket.h
    sys/accept.c--> sys/un.h
    sys/accept.c--> net/netlib.h
    sys/accept.c--> net/gen/in.h
    sys/accept.c--> net/gen/tcp.h
    sys/accept.c--> net/gen/tcp_io.h
    sys/accept.c--> net/gen/udp.h
    sys/accept.c--> net/gen/udp_io.h
    sys/getgroups.c--> sys/cdefs.h
    sys/getgroups.c--> namespace.h
    sys/getgroups.c--> lib.h
    sys/getgroups.c--> string.h
    sys/getgroups.c--> unistd.h
    sys/fchmod.c--> sys/cdefs.h
    sys/fchmod.c--> namespace.h
    sys/fchmod.c--> lib.h
    sys/fchmod.c--> string.h
    sys/fchmod.c--> sys/stat.h
    sys/_mcontext.c--> sys/cdefs.h
    sys/_mcontext.c--> lib.h
    sys/_mcontext.c--> namespace.h
    sys/_mcontext.c--> string.h
    sys/_mcontext.c--> ucontext.h
    sys/_mcontext.c--> unistd.h
    sys/link.c--> sys/cdefs.h
    sys/link.c--> namespace.h
    sys/link.c--> lib.h
    sys/link.c--> string.h
    sys/link.c--> unistd.h
    sys/access.c--> sys/cdefs.h
    sys/access.c--> namespace.h
    sys/access.c--> lib.h
    sys/access.c--> string.h
    sys/access.c--> unistd.h
    sys/chown.c--> sys/cdefs.h
    sys/chown.c--> namespace.h
    sys/chown.c--> lib.h
    sys/chown.c--> string.h
    sys/chown.c--> unistd.h
    sys/nanosleep.c--> sys/cdefs.h
    sys/nanosleep.c--> namespace.h
    sys/nanosleep.c--> lib.h
    sys/nanosleep.c--> unistd.h
    sys/nanosleep.c--> errno.h
    sys/nanosleep.c--> time.h
    sys/nanosleep.c--> sys/select.h
    sys/nanosleep.c--> sys/time.h
    sys/__getcwd.c--> sys/cdefs.h
    sys/__getcwd.c--> namespace.h
    sys/__getcwd.c--> sys/types.h
    sys/__getcwd.c--> sys/stat.h
    sys/__getcwd.c--> errno.h
    sys/__getcwd.c--> unistd.h
    sys/__getcwd.c--> dirent.h
    sys/__getcwd.c--> limits.h
    sys/__getcwd.c--> string.h
    sys/clock_settime.c--> sys/cdefs.h
    sys/clock_settime.c--> lib.h
    sys/clock_settime.c--> namespace.h
    sys/clock_settime.c--> string.h
    sys/clock_settime.c--> time.h
    sys/fpathconf.c--> sys/cdefs.h
    sys/fpathconf.c--> namespace.h
    sys/fpathconf.c--> lib.h
    sys/fpathconf.c--> sys/stat.h
    sys/fpathconf.c--> errno.h
    sys/fpathconf.c--> limits.h
    sys/fpathconf.c--> unistd.h
    sys/fpathconf.c--> termios.h
    sys/stat.c--> sys/cdefs.h
    sys/stat.c--> namespace.h
    sys/stat.c--> lib.h
    sys/stat.c--> sys/stat.h
    sys/stat.c--> string.h
    sys/adjtime.c--> sys/cdefs.h
    sys/adjtime.c--> lib.h
    sys/adjtime.c--> namespace.h
    sys/adjtime.c--> string.h
    sys/adjtime.c--> sys/time.h
    sys/adjtime.c--> time.h
    sys/fsync.c--> sys/cdefs.h
    sys/fsync.c--> namespace.h
    sys/fsync.c--> lib.h
    sys/fsync.c--> string.h
    sys/fsync.c--> unistd.h
    sys/shmat.c--> sys/cdefs.h
    sys/shmat.c--> lib.h
    sys/shmat.c--> namespace.h
    sys/shmat.c--> minix/rs.h
    sys/shmat.c--> lib.h
    sys/shmat.c--> sys/types.h
    sys/shmat.c--> sys/ipc.h
    sys/shmat.c--> sys/shm.h
    sys/shmat.c--> stdlib.h
    sys/shmat.c--> errno.h
    sys/shmat.c--> string.h
    sys/sigpending.c--> sys/cdefs.h
    sys/sigpending.c--> lib.h
    sys/sigpending.c--> namespace.h
    sys/sigpending.c--> string.h
    sys/sigpending.c--> signal.h
    sys/priority.c--> sys/cdefs.h
    sys/priority.c--> namespace.h
    sys/priority.c--> errno.h
    sys/priority.c--> sys/types.h
    sys/priority.c--> sys/resource.h
    sys/priority.c--> lib.h
    sys/priority.c--> unistd.h
    sys/priority.c--> string.h
    sys/priority.c--> stddef.h
    sys/mknod.c--> sys/cdefs.h
    sys/mknod.c--> namespace.h
    sys/mknod.c--> lib.h
    sys/mknod.c--> string.h
    sys/mknod.c--> stdlib.h
    sys/mknod.c--> unistd.h
    sys/mknod.c--> sys/stat.h
    sys/utimes.c--> sys/cdefs.h
    sys/utimes.c--> namespace.h
    sys/utimes.c--> lib.h
    sys/utimes.c--> sys/stat.h
    sys/utimes.c--> sys/time.h
    sys/utimes.c--> string.h
    sys/utimes.c--> errno.h
    sys/shmget.c--> sys/cdefs.h
    sys/shmget.c--> lib.h
    sys/shmget.c--> namespace.h
    sys/shmget.c--> minix/rs.h
    sys/shmget.c--> sys/types.h
    sys/shmget.c--> sys/ipc.h
    sys/shmget.c--> sys/shm.h
    sys/shmget.c--> stdlib.h
    sys/shmget.c--> errno.h
    sys/shmget.c--> string.h
    sys/close.c--> sys/cdefs.h
    sys/close.c--> namespace.h
    sys/close.c--> lib.h
    sys/close.c--> string.h
    sys/close.c--> unistd.h
    sys/statvfs.c--> sys/cdefs.h
    sys/statvfs.c--> lib.h
    sys/statvfs.c--> namespace.h
    sys/statvfs.c--> sys/types.h
    sys/statvfs.c--> sys/statvfs.h
    sys/statvfs.c--> string.h
    sys/getdents.c--> sys/cdefs.h
    sys/getdents.c--> namespace.h
    sys/getdents.c--> lib.h
    sys/getdents.c--> string.h
    sys/getdents.c--> dirent.h
    sys/open.c--> sys/cdefs.h
    sys/open.c--> namespace.h
    sys/open.c--> lib.h
    sys/open.c--> fcntl.h
    sys/open.c--> stdarg.h
    sys/open.c--> string.h
    sys/sbrk.c--> sys/cdefs.h
    sys/sbrk.c--> namespace.h
    sys/sbrk.c--> lib.h
    sys/sbrk.c--> unistd.h
    sys/select.c--> sys/cdefs.h
    sys/select.c--> lib.h
    sys/select.c--> namespace.h
    sys/select.c--> string.h
    sys/select.c--> sys/time.h
    sys/select.c--> sys/select.h
    sys/posix_spawn.c--> sys/cdefs.h
    sys/posix_spawn.c--> sys/queue.h
    sys/posix_spawn.c--> sys/wait.h
    sys/posix_spawn.c--> errno.h
    sys/posix_spawn.c--> fcntl.h
    sys/posix_spawn.c--> sched.h
    sys/posix_spawn.c--> spawn.h
    sys/posix_spawn.c--> signal.h
    sys/posix_spawn.c--> stdlib.h
    sys/posix_spawn.c--> string.h
    sys/posix_spawn.c--> unistd.h
    sys/futimens.c--> sys/cdefs.h
    sys/futimens.c--> namespace.h
    sys/futimens.c--> lib.h
    sys/futimens.c--> string.h
    sys/futimens.c--> sys/stat.h
    sys/setitimer.c--> sys/cdefs.h
    sys/setitimer.c--> namespace.h
    sys/setitimer.c--> lib.h
    sys/setitimer.c--> string.h
    sys/setitimer.c--> sys/time.h
    sys/sigreturn.c--> namespace.h
    sys/sigreturn.c--> sys/cdefs.h
    sys/sigreturn.c--> lib.h
    sys/sigreturn.c--> string.h
    sys/sigreturn.c--> assert.h
    sys/sigreturn.c--> signal.h
    sys/sigreturn.c--> string.h
    sys/sigreturn.c--> sys/signal.h
    sys/sigreturn.c--> machine/signal.h
    sys/syscall.c--> sys/cdefs.h
    sys/syscall.c--> lib.h
    sys/syscall.c--> namespace.h
    sys/shutdown.c--> sys/cdefs.h
    sys/shutdown.c--> namespace.h
    sys/shutdown.c--> lib.h
    sys/shutdown.c--> string.h
    sys/shutdown.c--> errno.h
    sys/shutdown.c--> stdio.h
    sys/shutdown.c--> sys/ioctl.h
    sys/shutdown.c--> sys/socket.h
    sys/shutdown.c--> sys/un.h
    sys/shutdown.c--> net/gen/in.h
    sys/shutdown.c--> net/gen/tcp.h
    sys/shutdown.c--> net/gen/tcp_io.h
    sys/lseek.c--> sys/cdefs.h
    sys/lseek.c--> namespace.h
    sys/lseek.c--> lib.h
    sys/lseek.c--> string.h
    sys/lseek.c--> minix/u64.h
    sys/lseek.c--> unistd.h
    sys/socket.c--> sys/cdefs.h
    sys/socket.c--> namespace.h
    sys/socket.c--> lib.h
    sys/socket.c--> errno.h
    sys/socket.c--> fcntl.h
    sys/socket.c--> signal.h
    sys/socket.c--> stdio.h
    sys/socket.c--> string.h
    sys/socket.c--> unistd.h
    sys/socket.c--> sys/socket.h
    sys/socket.c--> sys/ioctl.h
    sys/socket.c--> sys/ioc_net.h
    sys/socket.c--> net/hton.h
    sys/socket.c--> net/gen/in.h
    sys/socket.c--> net/gen/ether.h
    sys/socket.c--> net/gen/eth_hdr.h
    sys/socket.c--> net/gen/eth_io.h
    sys/socket.c--> net/gen/ip_hdr.h
    sys/socket.c--> net/gen/ip_io.h
    sys/socket.c--> net/gen/udp.h
    sys/socket.c--> net/gen/udp_hdr.h
    sys/socket.c--> net/gen/udp_io.h
    sys/socket.c--> net/gen/dhcp.h
    sys/socket.c--> net/netlib.h
    sys/socket.c--> netinet/in.h
    sys/setgid.c--> sys/cdefs.h
    sys/setgid.c--> lib.h
    sys/setgid.c--> namespace.h
    sys/setgid.c--> string.h
    sys/setgid.c--> unistd.h
    sys/mkfifo.c--> sys/cdefs.h
    sys/mkfifo.c--> namespace.h
    sys/mkfifo.c--> lib.h
    sys/mkfifo.c--> sys/stat.h
    sys/mkfifo.c--> unistd.h
    sys/stime.c--> sys/cdefs.h
    sys/stime.c--> namespace.h
    sys/stime.c--> minix/sysutil.h
    sys/stime.c--> lib.h
    sys/stime.c--> string.h
    sys/stime.c--> time.h
    sys/fstatfs.c--> sys/cdefs.h
    sys/fstatfs.c--> lib.h
    sys/fstatfs.c--> namespace.h
    sys/fstatfs.c--> sys/stat.h
    sys/fstatfs.c--> sys/statfs.h
    sys/fstatfs.c--> sys/statvfs.h
    sys/vfork.c--> sys/cdefs.h
    sys/vfork.c--> namespace.h
    sys/vfork.c--> lib.h
    sys/vfork.c--> string.h
    sys/vfork.c--> unistd.h
    sys/sendmsg.c--> sys/cdefs.h
    sys/sendmsg.c--> namespace.h
    sys/sendmsg.c--> lib.h
    sys/sendmsg.c--> errno.h
    sys/sendmsg.c--> stdlib.h
    sys/sendmsg.c--> string.h
    sys/sendmsg.c--> sys/ioctl.h
    sys/sendmsg.c--> sys/ioc_net.h
    sys/sendmsg.c--> sys/socket.h
    sys/sendmsg.c--> sys/types.h
    sys/sendmsg.c--> sys/un.h
    sys/fork.c--> sys/cdefs.h
    sys/fork.c--> namespace.h
    sys/fork.c--> lib.h
    sys/fork.c--> string.h
    sys/fork.c--> unistd.h
    sys/sem.c--> sys/cdefs.h
    sys/sem.c--> lib.h
    sys/sem.c--> namespace.h
    sys/sem.c--> lib.h
    sys/sem.c--> minix/rs.h
    sys/sem.c--> sys/types.h
    sys/sem.c--> sys/ipc.h
    sys/sem.c--> sys/sem.h
    sys/sem.c--> stdlib.h
    sys/sem.c--> stdarg.h
    sys/sem.c--> errno.h
    sys/sem.c--> string.h
    sys/mount.c--> sys/cdefs.h
    sys/mount.c--> namespace.h
    sys/mount.c--> lib.h
    sys/mount.c--> string.h
    sys/mount.c--> sys/mount.h
    sys/mount.c--> stdlib.h
    sys/mount.c--> stdio.h
    sys/mount.c--> sys/stat.h
    sys/mount.c--> minix/paths.h
    sys/mount.c--> minix/rs.h
    sys/mount.c--> minix/syslib.h
    sys/mount.c--> unistd.h
    sys/recvmsg.c--> sys/cdefs.h
    sys/recvmsg.c--> namespace.h
    sys/recvmsg.c--> lib.h
    sys/recvmsg.c--> errno.h
    sys/recvmsg.c--> stdio.h
    sys/recvmsg.c--> stdlib.h
    sys/recvmsg.c--> string.h
    sys/recvmsg.c--> sys/ioctl.h
    sys/recvmsg.c--> sys/ioc_net.h
    sys/recvmsg.c--> sys/socket.h
    sys/recvmsg.c--> sys/types.h
    sys/recvmsg.c--> sys/un.h
    sys/setsockopt.c--> sys/cdefs.h
    sys/setsockopt.c--> namespace.h
    sys/setsockopt.c--> lib.h
    sys/setsockopt.c--> string.h
    sys/setsockopt.c--> assert.h
    sys/setsockopt.c--> errno.h
    sys/setsockopt.c--> stdio.h
    sys/setsockopt.c--> sys/ioctl.h
    sys/setsockopt.c--> sys/socket.h
    sys/setsockopt.c--> sys/types.h
    sys/setsockopt.c--> netinet/tcp.h
    sys/setsockopt.c--> net/gen/in.h
    sys/setsockopt.c--> net/gen/tcp.h
    sys/setsockopt.c--> net/gen/tcp_io.h
    sys/setsockopt.c--> net/gen/udp.h
    sys/setsockopt.c--> net/gen/udp_io.h
    sys/getvfsstat.c--> sys/cdefs.h
    sys/getvfsstat.c--> lib.h
    sys/getvfsstat.c--> namespace.h
    sys/getvfsstat.c--> string.h
    sys/getvfsstat.c--> sys/statvfs.h
    sys/getrusage.c--> sys/cdefs.h
    sys/getrusage.c--> namespace.h
    sys/getrusage.c--> lib.h
    sys/getrusage.c--> string.h
    sys/getrusage.c--> unistd.h
    sys/getrusage.c--> sys/resource.h
    sys/flock.c--> sys/cdefs.h
    sys/flock.c--> namespace.h
    sys/flock.c--> lib.h
    sys/flock.c--> sys/types.h
    sys/flock.c--> fcntl.h
    sys/flock.c--> string.h
    sys/flock.c--> errno.h
    sys/flock.c--> unistd.h
    sys/dup2.c--> sys/cdefs.h
    sys/dup2.c--> namespace.h
    sys/dup2.c--> lib.h
    sys/dup2.c--> fcntl.h
    sys/dup2.c--> unistd.h
    sys/getrlimit.c--> sys/cdefs.h
    sys/getrlimit.c--> namespace.h
    sys/getrlimit.c--> errno.h
    sys/getrlimit.c--> limits.h
    sys/getrlimit.c--> sys/resource.h
    sys/getrlimit.c--> unistd.h
    sys/sigaction.c--> sys/cdefs.h
    sys/sigaction.c--> lib.h
    sys/sigaction.c--> namespace.h
    sys/sigaction.c--> string.h
    sys/sigaction.c--> signal.h
    sys/fchown.c--> sys/cdefs.h
    sys/fchown.c--> namespace.h
    sys/fchown.c--> lib.h
    sys/fchown.c--> string.h
    sys/fchown.c--> unistd.h
    sys/write.c--> sys/cdefs.h
    sys/write.c--> lib.h
    sys/write.c--> namespace.h
    sys/write.c--> string.h
    sys/write.c--> unistd.h
    sys/issetugid.c--> sys/cdefs.h
    sys/issetugid.c--> namespace.h
    sys/issetugid.c--> lib.h
    sys/issetugid.c--> string.h
    sys/issetugid.c--> unistd.h
    sys/rename.c--> sys/cdefs.h
    sys/rename.c--> lib.h
    sys/rename.c--> namespace.h
    sys/rename.c--> string.h
    sys/rename.c--> stdio.h
    sys/wait4.c--> sys/cdefs.h
    sys/wait4.c--> lib.h
    sys/wait4.c--> namespace.h
    sys/wait4.c--> string.h
    sys/wait4.c--> sys/wait.h
    sys/vectorio.c--> sys/cdefs.h
    sys/vectorio.c--> lib.h
    sys/vectorio.c--> namespace.h
    sys/vectorio.c--> assert.h
    sys/vectorio.c--> errno.h
    sys/vectorio.c--> limits.h
    sys/vectorio.c--> stdlib.h
    sys/vectorio.c--> string.h
    sys/vectorio.c--> sys/stat.h
    sys/vectorio.c--> sys/param.h
    sys/vectorio.c--> sys/uio.h
    sys/vectorio.c--> unistd.h
    sys/m_closefrom.c--> sys/cdefs.h
    sys/m_closefrom.c--> namespace.h
    sys/m_closefrom.c--> lib.h
    sys/m_closefrom.c--> stdlib.h
    sys/m_closefrom.c--> unistd.h
    sys/setrlimit.c--> sys/cdefs.h
    sys/setrlimit.c--> namespace.h
    sys/setrlimit.c--> errno.h
    sys/setrlimit.c--> limits.h
    sys/setrlimit.c--> sys/resource.h
    sys/setrlimit.c--> unistd.h
    sys/getsockname.c--> sys/cdefs.h
    sys/getsockname.c--> namespace.h
    sys/getsockname.c--> lib.h
    sys/getsockname.c--> errno.h
    sys/getsockname.c--> stdio.h
    sys/getsockname.c--> string.h
    sys/getsockname.c--> sys/ioctl.h
    sys/getsockname.c--> sys/socket.h
    sys/getsockname.c--> netinet/in.h
    sys/getsockname.c--> net/gen/in.h
    sys/getsockname.c--> net/gen/tcp.h
    sys/getsockname.c--> net/gen/tcp_io.h
    sys/getsockname.c--> net/gen/udp.h
    sys/getsockname.c--> net/gen/udp_io.h
    sys/getsockname.c--> sys/un.h
    sys/getpid.c--> sys/cdefs.h
    sys/getpid.c--> namespace.h
    sys/getpid.c--> lib.h
    sys/getpid.c--> string.h
    sys/getpid.c--> unistd.h
    sys/execve.c--> sys/cdefs.h
    sys/execve.c--> namespace.h
    sys/execve.c--> lib.h
    sys/execve.c--> unistd.h
    sys/execve.c--> string.h
    sys/execve.c--> stddef.h
    sys/execve.c--> minix/param.h
    sys/execve.c--> sys/exec_elf.h
    sys/execve.c--> sys/exec.h
    sys/sigsuspend.c--> sys/cdefs.h
    sys/sigsuspend.c--> lib.h
    sys/sigsuspend.c--> namespace.h
    sys/sigsuspend.c--> string.h
    sys/sigsuspend.c--> signal.h
    sys/getuid.c--> sys/cdefs.h
    sys/getuid.c--> namespace.h
    sys/getuid.c--> lib.h
    sys/getuid.c--> string.h
    sys/getuid.c--> unistd.h
    sys/setpgid.c--> sys/cdefs.h
    sys/setpgid.c--> lib.h
    sys/setpgid.c--> namespace.h
    sys/setpgid.c--> string.h
    sys/setpgid.c--> unistd.h
    sys/chdir.c--> sys/cdefs.h
    sys/chdir.c--> namespace.h
    sys/chdir.c--> lib.h
    sys/chdir.c--> string.h
    sys/chdir.c--> unistd.h
    sys/ftruncate.c--> sys/cdefs.h
    sys/ftruncate.c--> namespace.h
    sys/ftruncate.c--> lib.h
    sys/ftruncate.c--> minix/u64.h
    sys/ftruncate.c--> string.h
    sys/ftruncate.c--> unistd.h
    gen/itoa.c--> lib.h
    gen/clock.c--> sys/cdefs.h
    gen/clock.c--> namespace.h
    gen/clock.c--> time.h
    gen/clock.c--> sys/times.h
    gen/fsversion.c--> sys/types.h
    gen/fsversion.c--> minix/config.h
    gen/fsversion.c--> minix/const.h
    gen/fsversion.c--> minix/minlib.h
    gen/fsversion.c--> minix/type.h
    gen/fsversion.c--> fcntl.h
    gen/fsversion.c--> unistd.h
    gen/fsversion.c--> stdio.h
    gen/fsversion.c--> string.h
    gen/fsversion.c--> mfs/const.h
    gen/fslib.c--> minix/config.h
    gen/fslib.c--> limits.h
    gen/fslib.c--> dirent.h
    gen/fslib.c--> assert.h
    gen/fslib.c--> stdlib.h
    gen/fslib.c--> sys/types.h
    gen/fslib.c--> minix/const.h
    gen/fslib.c--> minix/type.h
    gen/fslib.c--> minix/minlib.h
    gen/fslib.c--> minix/ipc.h
    gen/fslib.c--> mfs/const.h
    gen/fslib.c--> mfs/type.h
    gen/fslib.c--> mfs/inode.h
    gen/fslib.c--> mfs/super.h
    gen/fslib.c--> minix/fslib.h
    gen/gcov_flush.c--> sys/types.h
    gen/gcov_flush.c--> stdio.h
    gen/gcov_flush.c--> stdlib.h
    gen/gcov_flush.c--> minix/gcov.h
    gen/configfile.c--> minix/stubs.h
    gen/configfile.c--> sys/types.h
    gen/configfile.c--> stdio.h
    gen/configfile.c--> stddef.h
    gen/configfile.c--> stdlib.h
    gen/configfile.c--> errno.h
    gen/configfile.c--> string.h
    gen/configfile.c--> time.h
    gen/configfile.c--> sys/stat.h
    gen/configfile.c--> minix/asciictype.h
    gen/configfile.c--> ctype.h
    gen/configfile.c--> configfile.h
    gen/configfile.c--> unistd.h
    gen/raise.c--> sys/types.h
    gen/raise.c--> signal.h
    gen/stderr.c--> lib.h
    gen/stderr.c--> sys/types.h
    gen/stderr.c--> unistd.h
    gen/stderr.c--> minix/minlib.h
    gen/getpass.c--> sys/cdefs.h
    gen/getpass.c--> namespace.h
    gen/getpass.c--> sys/types.h
    gen/getpass.c--> fcntl.h
    gen/getpass.c--> unistd.h
    gen/getpass.c--> signal.h
    gen/getpass.c--> termios.h
    gen/getpass.c--> string.h
    gen/gcov.c--> sys/types.h
    gen/gcov.c--> stdio.h
    gen/gcov.c--> stdlib.h
    gen/gcov.c--> minix/gcov.h
    gen/mtab.c--> sys/types.h
    gen/mtab.c--> lib.h
    gen/mtab.c--> minix/minlib.h
    gen/mtab.c--> ctype.h
    gen/mtab.c--> fcntl.h
    gen/mtab.c--> stdlib.h
    gen/mtab.c--> string.h
    gen/mtab.c--> unistd.h
    gen/mtab.c--> stdio.h
    gen/read_tsc_64.c--> minix/u64.h
    gen/read_tsc_64.c--> minix/minlib.h
    arch/i386/_cpufeature.c--> sys/types.h
    arch/i386/_cpufeature.c--> stdint.h
    arch/i386/_cpufeature.c--> minix/minlib.h
    arch/i386/_cpufeature.c--> minix/cpufeature.h
    arch/i386/_cpufeature.c--> machine/vm.h
    arch/i386/_cpufeature.c--> string.h
    arch/arm/read_tsc.c--> sys/types.h
    arch/arm/read_tsc.c--> minix/minlib.h
